//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface MSDocumentData : NSObject

@property(readonly, nonatomic) NSDictionary *symbolMap; // @synthesize symbolMap=_symbolMap;

- (void)purgeForeignSymbols;
- (id)symbolsReferencedBySymbolInstances;
- (id)symbolsReferencedBySymbolMasters;
- (id)symbolsReferencedByInstances:(id)arg1;
- (void)invalidateAffectedSymbolInstances;
- (void)addSymbolMaster:(id)arg1;
- (id)symbolWithID:(id)arg1;
- (id)allSymbols;
- (id)localSymbols;
- (id)symbolsPageOrCreateIfNecessary;
- (id)symbolsPage;

@end

