//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  6 2018 12:02:43).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface MSSymbolMaster : NSObject

@property(nonatomic) BOOL isDirty; // @synthesize isDirty=_isDirty;
@property(nonatomic) long long changeIdentifier; // @synthesize changeIdentifier=_changeIdentifier;
@property(readonly, nonatomic) NSSet *nestedSymbols;
@property(readonly, nonatomic) NSArray *allInstances;
@property(readonly, nonatomic) NSArray *allInfluencedInstances;
@property(readonly, nonatomic) NSArray *availableOverrides;
@property(readonly, nonatomic) NSString *name;

- (id)parentSymbol;
- (id)rootForNameUniquing;
- (BOOL)hasInstances;
- (id)nestedSymbolsSkipping:(id)arg1;
- (id)newSymbolInstance;
- (id)copyWithIDMapping:(id)arg1;
- (void)invalidateModifiedSymbolCache;
- (void)invalidateImmutableObject;
- (void)syncPropertiesFromObject:(id)arg1;
- (void)performInitWithImmutableModelObject:(id)arg1;
- (id)unselectedPreviewTemplateImage;
- (id)selectedPreviewTemplateImage;
- (void)applyStyleToMenuItem:(id)arg1 withColorSpace:(id)arg2;
- (BOOL)previewShouldIndicateSharedStyle;
- (void)applyOverrides:(id)arg1 document:(id)arg2;

@end

